### PR TITLE
[Issue #37] - Fix warning in sample test run

### PR DESCRIPTION
**Pull request by tedcasey**
## Description
Fixing Warning generated in sample server from sample tests

## Related Issue
37

## Motivation and Context
Remove Sample possible confusion

## How Has This Been Tested?
Run all tests

## Screenshots (if appropriate):
N/A
## Types of changes
Added Conditional to SampleServiceController in the Sample service extension

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by enortonAtAdobe — COMMENTED** [review]
this may fix the specific warning, but only accounts for that case, not the other methods which also don't allow requst bodies

**Comment by tedcasey** [comment]
This is only in samples.  Only meant for learning purposes.  This change is just meant to not confuse Ride newbies with warnings that might appear in the console when running the sample tests against the sample service server.  It's not meant to be comprehensive.

**Review by enortonAtAdobe — APPROVED** [review]
ok, but if a newbie follows (copies) this example, they might run into issues

**Comment by tedcasey** [comment]
Too many possible permutations and combinations to capture in samples.  This is just meant to give a flavor of how a Ride-driven test framework might be implemented.

**Pull request merged**
