### PR TITLE
Added method to modify the existing model object and list all the key…

### PR DESCRIPTION
**Pull request by ayush9999-qa**
…s including nested keys on the root object so that all keys can be fuzzed

## Description

With the help of added method, model object that is to be fuzzed and containing nested object will modified and all the nested keys will be added at the parent level and fuzz objects of all these keys will be created. These objects will then be used to original object for fuzzing.

## Related Issue
Fuzzing of low level (child) objects is not available #59

## Motivation and Context

This will help to fuzz all the child level objects.

## How Has This Been Tested?

Mocked this object and tried the final outcome of add method.

None

It is only used in 'populateFuzzSet' method and will not affect rest of the objects.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by tedcasey — COMMENTED** [review]
Hi Ayush,

Thanks for taking this on!  

I've reviewed the changes, but I would like to make sure the recursion logic is correct.  Can you test with more complex object, something like object in samples and send me a copy of the log that is generated?:

https://github.com/adobe/ride/blob/develop/sample/sample-product-group-shared-resources/src/main/resources/schemas/SampleService/profile.json

Thanks again!

**Comment by ayush9999-qa** [comment]
Hello Ted,

I have tested with the sample json file that you have sent. Object to be
fuzzed created using new and old code is same (stated below) which shows
that rest of the properties remain intact and only the nested objects get
shifted to the root level.'

Please see the object below:

> {
>     "sourceId": {
>         "type": "string"
>     },
>     "xid": {
>         "type": "string"
>     },
>     "record": {
>         "$ref": "#/definitions/record"
>     },
>     "timestamp": {
>         "format": "timestamp",
>         "description": "custom format will need to be handled in
> modelObject",
>         "type": "string"
>     }
> }
>

Please let me know if this can be merged.

Thanks and regards,
Ayush Goel

**Comment by tedcasey** [comment]
Hi Ayush,

If that schema does not recurse through the fuzzer with the new code, then it will need to be changed.  Ride advertises that it works with any arbitrary schema and, while support for certain schema properties is lacking in certain areas, basic schemas with library and value refs and complex interaction between them should work with any new functionality.

Unfortunately, I can’t look at code change presently, but I’ll take a look soon.

I’ll let you know as soon as I have something.  Also, let me know if you make a change before I get to it and I’ll take a second look.

Thanks!

Ted

**Comment by ayush9999-qa** [comment]
Hello Ted,

Thanks for the feedback.

The reason why I was *not* getting all properties at the root level is
because I am creating new ModelObject using the json schema and passing the
properties of that schema to the new function that I have created. Because
of this, object given in the 'definitions' section of the schema is not
getting substituted in the entire object. However, if I remove the
'definitions' section and substitute all the definitions in the json file
with given definition objects, then object is getting changed and all the
properties are added at the root level as expected.

I have also made a change in the code to add items of array at the root
level. Earlier, only objects of type 'OBJECT' was getting recursed but now
objects of type 'ARRAY' are also getting recursed.

Please find the sample json file used and output objects attached to this
email.

Thanks again for your help.

Regards,
Ayush Goel

**Comment by tedcasey** [comment]
Pulled your branch.  Compiling and taking a look locally.

**Review by tedcasey — COMMENTED** [review]
Hi Ayush,

After looking at your changes and walking through the code a bit to refresh my memory, I don't believe that these changes will be sufficient to completely walk and fuzz an arbitrary schema.

To illustrate this, try fuzzing "profile.json" schema in the Ride samples with your changes: https://github.com/adobe/ride/blob/develop/sample/sample-product-group-shared-resources/src/main/resources/schemas/SampleService/profile.json

I believe what needs to happen here is a refactor of the MetadataFuzzer and perhaps the MetadataEngine.  Currently the fuzzer simply gleans the top level properties.  What it needs to do is create a ModelObject instance (or use a created one) of the schema to be fuzzed, walk the model (ModelObject:property) of the instance, map fuzzed values back to the instance looping through the fuzzing data, and correctly populate and return the result set before completing the entire operation.  

What makes all this a little tricky is that in order to make this process fairly simple for the Ride developer, Ride relies on the [TestNG @Factory](https://testng.org/doc/documentation-main.html#factories) annotation to drive the process.

This is a fairly complex change and probably needs my direct involvement.  I will try to schedule some time to get to this soon (will add notes to the issue to that effect).

If you find that you can get the fuzzer to properly fuzz the profile schema that I mention above, I'll be happy to review your comments and/or review new changes (my attempts with your code failed).  If you feel that you'd like to wait for my changes, I'll keep you in the loop and you can pull them when they are ready.  Without new changes that accomplish these things, we probably need to close the current PR. Again,  I appreciate the effort, and let me know if there is something new you'd like me to look at!

**Comment by tedcasey** [comment]
Closing this PR.  A superseding one will be available shortly.

**Pull request closed without merging**
